spring:
  messages:
    basename: messages/messages
server:
  port: 30003
  session:
    timeout: 14400
  servlet:
    contextPath: /
mybatis:
  mapper-locations: mapper/**/*.xml
mail:
  host: smtp.naver.com
  senderemail: blict@naver.com
  auth:
    user: blict
    password: qmfflrxm
push:
  url: https://fcm.googleapis.com/fcm/send
  apikey: 1
sms:
  vendor: 1
  key: 1
  secret: 1
  sender: ''
applicationName: nyamnyambox

#dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbcUrl: "jdbc:mysql://dev01.nnbox.net:13306/nnbox?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false&serverTimezone=Asia/Seoul&allowMultiQueries=true"
      ### LIVE DB ###
      #jdbcUrl: "jdbc:mysql://121.78.82.136:13306/nnbox?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false&serverTimezone=UTC&allowMultiQueries=true"
      ### STAGE DB ###
      #jdbcUrl: "jdbc:mysql://121.78.82.134:13306/nnbox?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false&serverTimezone=UTC&allowMultiQueries=true"
      username: admin
      password: zhstjxm!2
      driverClassName: com.mysql.cj.jdbc.Driver
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
cors:
  allowOrigin: http://localhost:3000
logging:
  level:
    com: 
      nnbox: DEBUG
  responseLength: 1000
testmode: true

#stage
---
spring:
  config:
    activate:
      on-profile: stage
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbcUrl: "jdbc:mysql://121.78.82.134:13306/nnbox?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false&serverTimezone=UTC"
      username: admin
      password: zhstjxm!2
      driverClassName: com.mysql.jdbc.Driver
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
server:
  ssl:
    key-store: /home/nnbox/nnbox/key/keyStore.jks
    key-store-password: siasiaqkrtm1!
    key-password: siasiaqkrtm1!
cors:
  allowOrigin: https://nnstage.nnbox.net:8000
logging:
  level:
    com: 
      nnbox: DEBUG
  file:
    path: /home/nnbox/nnbox/java/nnbox-admin-backend/logs
  maxHistory: 10
  responseLength: 1000
testmode: false

#prod
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbcUrl: "jdbc:mysql://nndb:13306/nnbox?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false&serverTimezone=UTC"
      username: admin
      password: zhstjxm!2
      driverClassName: com.mysql.jdbc.Driver
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
server:
  ssl:
    key-store: /home/nnbox/nnbox/key/rider.jks
    key-store-password: siasiaqkrtm1!
    key-password: siasiaqkrtm1!
cors:
  allowOrigin: https://drnana.nnbox.net:8000
logging:
  level:
    com: 
      nnbox: DEBUG
  file:
    path: /home/nnbox/nnbox/java/nnbox-admin-backend/logs
  maxHistory: 10
  responseLength: 1000
testmode: false

